stages:
    - compile
    - deploy
cache:
  paths:
    - node_modules/
    - .next/cache/`

compile_dev:
  stage: compile
  image: node:16
  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - .next/
  environment:
    name: development

#Deploy into the AWS layer based using the AWS credentials
deploy_dev:
  stage: deploy
  image: node:16
  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  before_script:
    - npm install -g serverless@2.72.3
  script:
    - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY} --secret ${AWS_SECRET_KEY} -o
    - serverless --debug
  needs:
    - job: compile_dev
      artifacts: true
  environment:
    name: development